// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagement.Data;

#nullable disable

namespace WarehouseManagement.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260512193139_AddIdentitySchema")]
    partial class AddIdentitySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("WarehouseManagement.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastCounted")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MinSafetyStock")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QuantityAllocated")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("CK_Inventory_Allocation", "QuantityAllocated <= QuantityOnHand");

                            t.HasCheckConstraint("CK_Inventory_NonNegative", "QuantityOnHand >= 0 AND QuantityAllocated >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d16947b-d100-4847-bc9e-127be8dc53c8"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(850),
                            IsActive = true,
                            ProductId = new Guid("652bafb1-dd00-4525-9b18-7bc138cf4e19"),
                            QuantityAllocated = 2,
                            QuantityOnHand = 12,
                            WarehouseId = new Guid("93b76b44-5c36-4e0f-9936-01ef16359b5d")
                        },
                        new
                        {
                            Id = new Guid("663a1e5c-c0b5-46d6-8f29-461be63e82bf"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(1720),
                            IsActive = true,
                            ProductId = new Guid("8863f7cc-ef0f-4686-9d81-b217376f608e"),
                            QuantityAllocated = 0,
                            QuantityOnHand = 30,
                            WarehouseId = new Guid("f07f2d6e-5176-47c8-bd34-46499b30556d")
                        },
                        new
                        {
                            Id = new Guid("8e46d376-2ebf-4036-803c-98b280aaf6e0"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(1730),
                            IsActive = true,
                            ProductId = new Guid("71e30164-cd71-47c0-b3d0-9e55b46a0a5f"),
                            QuantityAllocated = 1,
                            QuantityOnHand = 4,
                            WarehouseId = new Guid("f07f2d6e-5176-47c8-bd34-46499b30556d")
                        },
                        new
                        {
                            Id = new Guid("a280cc60-ddb6-41d4-8c77-e7236623e535"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(1740),
                            IsActive = true,
                            ProductId = new Guid("df1da8d1-8c53-488a-88eb-db24a4ac66bf"),
                            QuantityAllocated = 50,
                            QuantityOnHand = 500,
                            WarehouseId = new Guid("87261fbf-f45e-4f37-bce9-0ca4108311d2")
                        },
                        new
                        {
                            Id = new Guid("c43b9393-1a2f-4b43-aa3a-7f60e2650e73"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(1740),
                            IsActive = true,
                            ProductId = new Guid("dfdde47b-d9e7-4f12-9add-0881839f2e01"),
                            QuantityAllocated = 5,
                            QuantityOnHand = 45,
                            WarehouseId = new Guid("93b76b44-5c36-4e0f-9936-01ef16359b5d")
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WeightLbs")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e83fa4d-5c5b-4a97-bbfc-5794a316bf25"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(3650),
                            IsActive = true,
                            Name = "iPad Air 5th Gen 256GB",
                            ReorderLevel = 10,
                            SKU = "TAB-IP-AIR",
                            SupplierId = new Guid("e260c87f-7d35-4bc6-bf3b-7e43103a062f")
                        },
                        new
                        {
                            Id = new Guid("652bafb1-dd00-4525-9b18-7bc138cf4e19"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4240),
                            IsActive = true,
                            Name = "Ergonomic Task Chair V2",
                            ReorderLevel = 5,
                            SKU = "CHR-ERG-V2",
                            SupplierId = new Guid("f1869c9d-8a17-4f84-a121-194b9aa4b80c")
                        },
                        new
                        {
                            Id = new Guid("71e30164-cd71-47c0-b3d0-9e55b46a0a5f"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4250),
                            IsActive = true,
                            Name = "3-Ton Hydraulic Pallet Jack",
                            ReorderLevel = 2,
                            SKU = "IND-PLJ-3T",
                            SupplierId = new Guid("c886b05a-ed79-4682-88b1-276f9f573dbb")
                        },
                        new
                        {
                            Id = new Guid("8863f7cc-ef0f-4686-9d81-b217376f608e"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4260),
                            IsActive = true,
                            Name = "LG 27\" UltraFine 4K Monitor",
                            ReorderLevel = 20,
                            SKU = "MON-LG-27-4K",
                            SupplierId = new Guid("e260c87f-7d35-4bc6-bf3b-7e43103a062f")
                        },
                        new
                        {
                            Id = new Guid("bbbdd36f-811e-4053-9de1-b59fa8bfca39"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4260),
                            IsActive = true,
                            Name = "Electric Standing Desk 60x30",
                            ReorderLevel = 5,
                            SKU = "DSK-ST-ADJ",
                            SupplierId = new Guid("f1869c9d-8a17-4f84-a121-194b9aa4b80c")
                        },
                        new
                        {
                            Id = new Guid("db3a77f4-6571-4459-943f-537a142e0242"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4270),
                            IsActive = true,
                            Name = "Heavy Duty Pallet Racking Unit",
                            ReorderLevel = 10,
                            SKU = "IND-RACK-HD",
                            SupplierId = new Guid("c886b05a-ed79-4682-88b1-276f9f573dbb")
                        },
                        new
                        {
                            Id = new Guid("df1da8d1-8c53-488a-88eb-db24a4ac66bf"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4270),
                            IsActive = true,
                            Name = "Premium A4 Copy Paper (10 Reams)",
                            ReorderLevel = 100,
                            SKU = "OFF-PAP-A4",
                            SupplierId = new Guid("316c467d-3945-44bf-b139-b452ad108bda")
                        },
                        new
                        {
                            Id = new Guid("dfdde47b-d9e7-4f12-9add-0881839f2e01"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4280),
                            IsActive = true,
                            Name = "Dell Latitude 7420 Business Laptop",
                            ReorderLevel = 15,
                            SKU = "LAP-DL-7420",
                            SupplierId = new Guid("e260c87f-7d35-4bc6-bf3b-7e43103a062f")
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExpectedDeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PONumber")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("WarehouseManagement.Models.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("WarehouseManagement.Models.StockTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserPerformedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.HasIndex("UserPerformedBy");

                    b.HasIndex("WarehouseId");

                    b.ToTable("StockTrackings");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("316c467d-3945-44bf-b139-b452ad108bda"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 601, DateTimeKind.Utc).AddTicks(6720),
                            IsActive = true,
                            LeadTimeDays = 2,
                            Name = "Prime Paper & Supplies"
                        },
                        new
                        {
                            Id = new Guid("c886b05a-ed79-4682-88b1-276f9f573dbb"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 601, DateTimeKind.Utc).AddTicks(7450),
                            IsActive = true,
                            LeadTimeDays = 7,
                            Name = "Global Industrial Parts"
                        },
                        new
                        {
                            Id = new Guid("e260c87f-7d35-4bc6-bf3b-7e43103a062f"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 601, DateTimeKind.Utc).AddTicks(7510),
                            IsActive = true,
                            LeadTimeDays = 3,
                            Name = "NexGen Electronics"
                        },
                        new
                        {
                            Id = new Guid("f1869c9d-8a17-4f84-a121-194b9aa4b80c"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 601, DateTimeKind.Utc).AddTicks(7510),
                            IsActive = true,
                            LeadTimeDays = 14,
                            Name = "SteelCase Office Systems"
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReceivedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TransferNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex("TransferNumber")
                        .IsUnique();

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("WarehouseManagement.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f408d44-a9e1-4cd8-9c16-0f115bd78e60"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e53c5057-d28d-46e1-be61-2f2439bda7fc",
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(4760),
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "Robert Chen",
                            PhoneNumberConfirmed = false,
                            Position = "Inventory Specialist",
                            TwoFactorEnabled = false,
                            WarehouseId = new Guid("87261fbf-f45e-4f37-bce9-0ca4108311d2")
                        },
                        new
                        {
                            Id = new Guid("393e4fa6-84a0-4ea2-990a-d2ab42c641ca"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7ec2ff38-1588-4ee3-a170-e00033286ea5",
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(480),
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "John Smith",
                            PhoneNumberConfirmed = false,
                            Position = "Regional Manager",
                            TwoFactorEnabled = false,
                            WarehouseId = new Guid("93b76b44-5c36-4e0f-9936-01ef16359b5d")
                        },
                        new
                        {
                            Id = new Guid("799cd594-ac79-4436-abf3-2a1a57d76860"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "60adbdf3-30b1-4593-bc09-38a0dc06c7ec",
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 603, DateTimeKind.Utc).AddTicks(510),
                            EmailConfirmed = false,
                            IsActive = true,
                            LockoutEnabled = false,
                            Name = "Maria Garcia",
                            PhoneNumberConfirmed = false,
                            Position = "Warehouse Lead",
                            TwoFactorEnabled = false,
                            WarehouseId = new Guid("f07f2d6e-5176-47c8-bd34-46499b30556d")
                        });
                });

            modelBuilder.Entity("WarehouseManagement.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("CapacitySquareFeet")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("CurrentUtilizationPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87261fbf-f45e-4f37-bce9-0ca4108311d2"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(2460),
                            IsActive = true,
                            Name = "Chicago Logistics Hub",
                            WarehouseCode = "CHI-LOG-003"
                        },
                        new
                        {
                            Id = new Guid("88ebdcc4-708c-446c-ac98-2bad67233d9f"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(2840),
                            IsActive = true,
                            Name = "Dallas Fulfillment Center",
                            WarehouseCode = "DAL-FUL-004"
                        },
                        new
                        {
                            Id = new Guid("93b76b44-5c36-4e0f-9936-01ef16359b5d"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(2840),
                            IsActive = true,
                            Name = "New York Distribution Center",
                            WarehouseCode = "NY-DC-001"
                        },
                        new
                        {
                            Id = new Guid("f07f2d6e-5176-47c8-bd34-46499b30556d"),
                            CreatedAt = new DateTime(2026, 5, 12, 19, 31, 38, 602, DateTimeKind.Utc).AddTicks(2850),
                            IsActive = true,
                            Name = "Los Angeles West Coast Hub",
                            WarehouseCode = "LA-WH-002"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WarehouseManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarehouseManagement.Models.Inventory", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("Inventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("Inventories")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WarehouseManagement.Models.PurchaseOrder", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("PurchaseOrderLines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("WarehouseManagement.Models.StockTracking", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany("StockTrackings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.User", "User")
                        .WithMany("StockTrackings")
                        .HasForeignKey("UserPerformedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WarehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Transfer", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Warehouse", "FromWarehouse")
                        .WithMany("FromTransfers")
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarehouseManagement.Models.Warehouse", "ToWarehouse")
                        .WithMany("ToTransfers")
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromWarehouse");

                    b.Navigation("Product");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.User", b =>
                {
                    b.HasOne("WarehouseManagement.Models.Warehouse", "Warehouse")
                        .WithMany("Users")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Product", b =>
                {
                    b.Navigation("Inventories");

                    b.Navigation("PurchaseOrderLines");

                    b.Navigation("StockTrackings");
                });

            modelBuilder.Entity("WarehouseManagement.Models.PurchaseOrder", b =>
                {
                    b.Navigation("PurchaseOrderLines");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Supplier", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("WarehouseManagement.Models.User", b =>
                {
                    b.Navigation("StockTrackings");
                });

            modelBuilder.Entity("WarehouseManagement.Models.Warehouse", b =>
                {
                    b.Navigation("FromTransfers");

                    b.Navigation("Inventories");

                    b.Navigation("ToTransfers");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
